# Generated by Django 6.1.1 on 2026-09-12 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=255)),
                ('crop_type', models.CharField(max_length=255)),
                ('hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('health', models.IntegerField(default=0)),
                ('disease_risk', models.IntegerField(default=0)),
                ('pest_risk', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
